#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
from ruamel.yaml import YAML
import base64

def str_representer(dumper, data):
    if len(data.splitlines()) > 1:  # check for multiline string
        return dumper.represent_scalar('tag:yaml.org,2002:str', data, style='|')
    return dumper.represent_scalar('tag:yaml.org,2002:str', data)

def main():
    yaml = YAML(pure=True)
    yaml.default_flow_style = False
    yaml.representer.add_representer(str, str_representer)

    secret = yaml.load(sys.stdin.read())

    for key, value in secret["data"].items():
        secret["data"][key] = base64.b64decode(value.encode("utf-8")).decode("utf-8")

    yaml.dump(secret, sys.stdout)

if __name__ == "__main__":
    main()
